/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "bsp/stm32f4xx.h"
#include "driver/rcc.h"

int main(void)
{
	/*Test code*/
    GPIOA_CLK_EN();
    GPIOB_CLK_EN();
    GPIOC_CLK_EN();
    GPIOH_CLK_EN();

    GPIOA_CLK_DISABLE();
    GPIOB_CLK_DISABLE();
    GPIOC_CLK_DISABLE();
    GPIOH_CLK_DISABLE();

    /* Loop forever */
	for(;;);
}
