/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "bsp/stm32f4xx.h"
#include "driver/rcc.h"
#include "driver/gpio.h"

void delay(void)
{
    volatile uint32_t count = 0;
    for (count = 0; count < 400000; count++) {

    }
}

int main(void)
{
	GpioHandleTypeDef_t Handle;

	Handle.gpioBaseAddr = GPIOA;
	Handle.gpioConfig.pinNumber = GPIO_PIN_5;
	Handle.gpioConfig.gpioPinMode = GPIO_OUTPUT;
	Handle.gpioConfig.gpioOutputType = PUSH_PULL;
	
	gpioInit(&Handle);

	for(;;)
	{
	gpioPinWrite(&Handle, GPIO_PIN_5, GPIO_PIN_SET);
	delay();
	gpioPinWrite(&Handle, GPIO_PIN_5, GPIO_PIN_RESET);
	delay();
	}
}
