/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "bsp/stm32f4xx.h"
#include "driver/rcc.h"
#include "driver/gpio.h"
#include "driver/exti.h"

void delay(void)
{
    volatile uint32_t count = 0;
    for (count = 0; count < 400000; count++) {

    }
}
GpioHandleTypeDef_t Handle;
GpioHandleTypeDef_t Handle2;

int main(void)
{


	Handle.gpioBaseAddr = GPIOA;
	Handle.gpioConfig.pinNumber = GPIO_PIN_5;
	Handle.gpioConfig.gpioPinMode = GPIO_OUTPUT;
	Handle.gpioConfig.gpioOutputType = PUSH_PULL;
	
	Handle2.gpioBaseAddr = GPIOC;
	Handle2.gpioConfig.pinNumber = GPIO_PIN_13;
	Handle2.gpioConfig.gpioPinMode = GPIO_INPUT;
	Handle2.gpioConfig.gpioOutputType = PUSH_PULL;
	Handle2.gpioConfig.gpioPuPdSelection = NO_PUP_PDOWN;
	Handle2.gpioConfig.gpioInterruptDetectType = EXTI_TRIGGER_SELECTION_FT;
	gpioInit(&Handle);
	gpioInit(&Handle2);

	gpioInitIRQ(&Handle2, EXTI13, EXTI15_10_IRQ);

	while(1)
	{
		;

	}
}

void EXTI15_10_IRQHandler(void)
{
	ClearExtiInterrupts(EXTI13, EXTI15_10_IRQ);
	gpioTogglePin(&Handle, GPIO_PIN_5);
}
